version: '3'
services:
  app:
    build: .
    deploy:
      replicas: 4
    expose: 
    - "8080"

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on: 
      - app